import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { getDecisions, approveDecision, rejectDecision, requestReview } from '../api';
import { CheckCircle, XCircle, MessageSquare, RefreshCw, Filter } from 'lucide-react';
import {
  PageHeader, LoadingSpinner, EmptyState, ErrorBanner,
  ActionBadge, ConfidenceBar, FreshnessTag, ApprovalStatusBadge, ScoreDisplay,
} from '../components/ui';
import { formatDistanceToNow } from 'date-fns';

export default function Decisions() {
  const [page, setPage] = useState(1);
  const qc = useQueryClient();

  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ['decisions', page],
    queryFn: () => getDecisions({ page, pageSize: 20 }),
  });

  const approveMutation = useMutation({
    mutationFn: ({ id }: { id: string }) => approveDecision(id, { approvedBy: 'Sales Manager' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['decisions'] }),
  });

  const rejectMutation = useMutation({
    mutationFn: ({ id }: { id: string }) => rejectDecision(id, { rejectedBy: 'Sales Manager' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['decisions'] }),
  });

  const decisions = data?.data || [];
  const pagination = data?.pagination;

  return (
    <div className="p-8 animate-fade-in">
      <PageHeader
        title="AI Decisions"
        subtitle="Evidence-backed recommendations generated by TracePilot"
        badge={pagination?.total?.toString()}
        actions={
          <button onClick={() => refetch()} className="btn-ghost">
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
        }
      />

      {error && <ErrorBanner message="Failed to load decisions" onRetry={() => refetch()} />}

      {isLoading ? (
        <div className="flex items-center justify-center py-20">
          <LoadingSpinner size="lg" />
        </div>
      ) : decisions.length === 0 ? (
        <EmptyState
          title="No decisions yet"
          message="Ask TracePilot a business question to generate evidence-backed decisions."
          icon={<MessageSquare className="w-12 h-12 text-blue-400" />}
        />
      ) : (
        <div className="space-y-4">
          {decisions.map((d: {
            id: string;
            query: string;
            entityId?: string;
            entityType?: string;
            score?: number;
            rank?: number;
            recommendation?: string;
            rationale?: string;
            confidence?: number;
            createdAt: string;
            approvals?: Array<{ status: string }>;
            evidence?: Array<{ id: string; sourceType: string; field: string; value: string }>;
          }) => {
            const approval = d.approvals?.[0];
            const approvalStatus = approval?.status || 'PENDING';

            return (
              <div key={d.id} className="card">
                <div className="flex items-start gap-4">
                  {d.score && <ScoreDisplay score={d.score} />}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      {d.rank && <span className="badge badge-blue">Rank #{d.rank}</span>}
                      {d.recommendation && <ActionBadge action={d.recommendation} />}
                      <ApprovalStatusBadge status={approvalStatus} />
                    </div>
                    <p className="text-sm font-medium text-white mb-1 truncate">{d.entityId}</p>
                    <p className="text-xs mb-2" style={{ color: 'var(--text-muted)' }}>{d.query}</p>
                    {d.rationale && (
                      <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>
                        {d.rationale.slice(0, 120)}{d.rationale.length > 120 ? '...' : ''}
                      </p>
                    )}
                    {d.evidence && d.evidence.length > 0 && (
                      <div className="flex gap-2 mt-2 flex-wrap">
                        {d.evidence.slice(0, 3).map((ev: { id: string; sourceType: string; field: string; value: string }) => (
                          <span key={ev.id} className="badge badge-gray text-xs">
                            {ev.sourceType}: {ev.field}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                  <div className="shrink-0 text-right">
                    <div className="flex items-center gap-2 mb-2 justify-end">
                      <ConfidenceBar value={d.confidence || 0} />
                    </div>
                    <div className="text-xs mb-3" style={{ color: 'var(--text-muted)' }}>
                      {formatDistanceToNow(new Date(d.createdAt), { addSuffix: true })}
                    </div>
                    {approvalStatus === 'PENDING' && (
                      <div className="flex gap-2 justify-end">
                        <button
                          onClick={() => approveMutation.mutate({ id: d.id })}
                          disabled={approveMutation.isPending}
                          className="btn-success text-xs px-3 py-1.5"
                        >
                          <CheckCircle className="w-3.5 h-3.5" /> Approve
                        </button>
                        <button
                          onClick={() => rejectMutation.mutate({ id: d.id })}
                          disabled={rejectMutation.isPending}
                          className="btn-danger text-xs px-3 py-1.5"
                        >
                          <XCircle className="w-3.5 h-3.5" /> Reject
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })}

          {/* Pagination */}
          {pagination && pagination.pages > 1 && (
            <div className="flex items-center justify-center gap-3 pt-4">
              <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="btn-ghost text-sm">
                Previous
              </button>
              <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                Page {page} of {pagination.pages}
              </span>
              <button onClick={() => setPage(p => Math.min(pagination.pages, p + 1))} disabled={page === pagination.pages} className="btn-ghost text-sm">
                Next
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
